package com.devindi.mapper;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.*;

@SupportedSourceVersion(SourceVersion.RELEASE_7)
@SupportedAnnotationTypes({
        "com.devindi.mapper.Mapper"
})
public class MapperProcessor extends AbstractProcessor {

    private ProcessingEnvironment processingEnv;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
        super.init(processingEnv);
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element annotatedElement : roundEnv.getElementsAnnotatedWith(Mapper.class)) {
            ElementKind kind = annotatedElement.getKind();
            if (kind.equals(ElementKind.INTERFACE)) {
                createInterfaceImplementation((TypeElement) annotatedElement);
            } else {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING, "Mapper supports interfaces only", annotatedElement);
                return false;
            }
        }
        return false;
    }

    private void createInterfaceImplementation(TypeElement interfaceElement) {
        TypeSpec.Builder implBuilder = TypeSpec.classBuilder(interfaceElement.getSimpleName() + "Impl")
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(ClassName.get(interfaceElement));

        for (Element element : interfaceElement.getEnclosedElements()) {
            if (element.getKind().equals(ElementKind.METHOD)) {
                MethodSpec methodSpec = generateMappingMethod((ExecutableElement) element);
                if (methodSpec != null) implBuilder.addMethod(methodSpec);
            }
        }

        TypeSpec implSpec = implBuilder.build();
        final JavaFile javaFile = JavaFile.builder(interfaceElement.getEnclosingElement().toString(), implSpec)
                .addFileComment("Generated by Mapping processor, do not modify")
                .build();

        try {
            final JavaFileObject sourceFile = processingEnv.getFiler().createSourceFile(
                    javaFile.packageName + "." + implSpec.name, interfaceElement);
            try (final Writer writer = new BufferedWriter(sourceFile.openWriter())) {
                javaFile.writeTo(writer);
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, e.getMessage(), interfaceElement);
        }
    }

    private MethodSpec generateMappingMethod(ExecutableElement methodElement) {
        VariableElement sourceElement = getParameterElement(methodElement);
        if (sourceElement == null) return null;

        TypeMirror targetType = getReturnType(methodElement);
        if (targetType == null) return null;

        String targetTypeName = targetType.toString();
        String sourceTypeName = sourceElement.asType().toString();

        Map<String, ExecutableElement> argumentGetters = getGetters(sourceTypeName);

        ExecutableElement constructorElement = getConstructorElement(targetTypeName);
        if (constructorElement == null) return null;
        List<? extends VariableElement> constructorParameters = constructorElement.getParameters();

        if (constructorParameters.size() != argumentGetters.size()) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.MANDATORY_WARNING, "Target constructor have different arguments count", methodElement);
        }

        //generate method code
        MethodSpec.Builder methodBuilder = MethodSpec.overriding(methodElement);
        StringBuilder statementBuilder = new StringBuilder();
        statementBuilder
                .append("return new ")
                .append(targetTypeName)
                .append("(");

        String separator = "";
        for (VariableElement constructorParameter : constructorParameters) {
            String parameterName = constructorParameter.getSimpleName().toString().toLowerCase();
            ExecutableElement getter = argumentGetters.get(parameterName);
            if (!constructorParameter.asType().equals(getter.getReturnType())) {
                //getter and constructor parameter have different types
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Getter return type and constructor argument type are different", methodElement);
            }

            statementBuilder
                    .append(separator)
                    .append('\n')
                    .append(methodElement.getParameters().get(0).getSimpleName())
                    .append(".")
                    .append(getter.getSimpleName())
                    .append("()");
            separator = ",";
        }

        statementBuilder
                .append('\n')
                .append(")");
        methodBuilder.addStatement(statementBuilder.toString());

        return methodBuilder.build();
    }

    private VariableElement getParameterElement(ExecutableElement element) {
        List<? extends VariableElement> parameters = element.getParameters();
        if (parameters.size() != 1) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING, "Mapper method should have only 1 parameter. Method will be ignored", element);
            return null;
        }
        return parameters.get(0);
    }

    private TypeMirror getReturnType(ExecutableElement element) {
        TypeMirror returnType = element.getReturnType();
        if (returnType.getKind().equals(TypeKind.VOID)) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING, "Mapper method should return value. Method will be ignored", element);
            return null;
        }
        return returnType;
    }

    private ExecutableElement getConstructorElement(String className) {
        TypeElement element = processingEnv.getElementUtils().getTypeElement(className);
        List<? extends Element> enclosedElements = element.getEnclosedElements();
        List<ExecutableElement> constructors = ElementFilter.constructorsIn(enclosedElements);
        if (constructors.size() != 1) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING, "Mapper target should have only 1 constructor. Method will be ignored", element);
            return null;
        }
        return constructors.get(0);
    }

    private Map<String, ExecutableElement> getGetters(String className) {
        Map<String, ExecutableElement> gettersMap = new HashMap<>();
        List<? extends Element> enclosedElements = processingEnv.getElementUtils().getTypeElement(className).getEnclosedElements();
        List<ExecutableElement> methodElements = ElementFilter.methodsIn(enclosedElements);
        for (ExecutableElement element : methodElements) {
            String methodName = element.getSimpleName().toString();
            if (methodName.startsWith("get") && element.getParameters().size() == 0) {
                gettersMap.put(methodName.substring(3).toLowerCase(), element);
            }
        }
        return gettersMap;
    }
}
